### ISSUE TITLE
1) Verify the assumptions of the project

### ISSUE THREAD

**Issue by namiyousef** [namiyousef/ai_hack_2021#2]
Please refer to #1 for a high level view of the entire project

The project makes a critical assumption: Low income neighbourhoods have LOW NOx levels. There are arguments for and against this, for example:

- Low income neighbourhoods may be next to industrial areas, leading to high NOx values
- High income areas may have more traffic, leading to high NOx values

To verify this, attributes that **explain** socioeconomic class will be used to cluster neighbourhoods into a pre-specified number of classes (i.e. low, medium or high class). The first method to try is K-means.

Once this has been done, the results will be compared to existing research that explains socioeconomic class (this can be a previous similar study using an alternative dataset, socioeconomic indexes, etc...). This step is necessary as it ensures that the clustering method used is reasonable and that the data that we have from this particular dataset is sufficient for what we are trying to do. 

At this point, thresholds for low, medium and high NOx values will be found from literature, and will be used to create a new attribute in the dataset that explains whether a datapoint has a high, low or medium NOx value. These will be compared with the clusters in order to verify the assumption.

```diff
! At this point the comparison will take the form of probabilities (i.e. given neighbourhood, probability of NOx class) 
```

Success Criteria:
- A clustering model capable of predicting clusters based on the dataset that we have
- Evidence that the clusters match that of the literature
- Evidence that the assumption is valid
- Thresholds for creating of NOx classes

**Comment by namiyousef** [comment]
Gone reasonably well - able to find low income areas, middle / high harder to distinguish. These are very high NOx areas though, which changes the narrative of the story in #1. This means that we want to make sure that developing these areas will not lead to higher  / dangerous NOx levels.

**Comment by RAV4ever** [comment]
Success criteria evaluation:

1) Created a k-means clustering model with 4 inputs: 'CMEDV','INDUS','AGE','LSTAT'. 
2) Clustering model correlates well with LSTAT and looks like the figure we obtained from the literature
3) Assumption was not valid afterall. Lower income areas have higher NOx due to more industry, greater density of roads.
4) 25 ppm exposure limit for 25 hour work shift, 50 ppm exposure for 50 hour workshift
