### ISSUE TITLE
2) Create a model for predicting NOx levels

### ISSUE THREAD

**Issue by namiyousef** [namiyousef/ai_hack_2021#4]
The data has NOx values in continuous format, which means that a regression model can be built. This would predict the NOx of a datapoint given parameters that are a combination of geographical data (i.e. latitude, longitude, distance from employment centres) and socioeconomic data (i.e. house price, crime, etc.).

The model needs to be able to predict with a reasonably high accuracy.

The first method to try is linear regression. Support Vector Regression may be required since some categorical variables may be quite informative. If needed, more complicated methods (i.e. neural nets) will be considered.

Success Criteria:
- A regression model capable of predicting NOx levels based on selected attributes
- Evidence that the regression model matches the assumptions (this includes checking for hetero/homoskedasticity, qq-plots to check normality of errors)

**Comment by RAV4ever** [comment]
Support Vector regression was used with an R squared of 0.85
