### ISSUE TITLE
Determine of LSTAT is sufficient for clustering neighbourhoods by income

### ISSUE THREAD

**Issue by namiyousef** [namiyousef/ai_hack_2021#9]
Use a decision tree cluster to fine clusters using LSTAT, does this compare with the map? Kmeans?

**Comment by RAV4ever** [comment]
Didn't have the chance to look at alternatives as we spent time trying to make our data normal before training kmeans

**Comment by RAV4ever** [comment]
LSTAT varies with cluster and correlates with the other variables such as median housing income
